### ISSUE TITLE
A request without `Content-Type` but with 'Content-Length' headers triggers TypeError

### ISSUE THREAD

**Issue by mishok13** [schubergphilis/microchassis#15]
Discovered accidentally when using HTTPie (which sets `Content-Length` by default if using `POST` verb):
```
$ curl -v -XPOST -H'Content-Length: 0' localhost:3101/v1/review
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3101 (#0)
> POST /v1/review HTTP/1.1
> Host: localhost:3101
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 0
>
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 47
< ETag: W/"2f-tlH54Mx08cpJrCC9a9wUExQ/iWA"
< Date: Wed, 11 Oct 2017 16:22:33 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
{"message":"Something went terribly wrong...."}
```

**Comment by mishok13** [comment]
And the error from backend point of view:
```
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.23969157Z TypeError: Cannot read property 'startsWith' of undefined
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239706846Z     at type (/app/node_modules/microchassis/src/http-server.ts:28:44)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239711445Z     at jsonParser (/app/node_modules/body-parser/lib/types/json.js:116:10)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239715423Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239718811Z     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239722203Z     at /app/node_modules/express/lib/router/index.js:284:7
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239725306Z     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239728278Z     at next (/app/node_modules/express/lib/router/index.js:275:10)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.23973123Z     at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239734178Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
appraisalservice-2758928751-hg6vk: 2017-10-11T16:22:33.239737251Z     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
```
